services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.deploy
      target: api
    restart: unless-stopped
    env_file:
      - path: .env
        required: false
    environment:
      APP_PORT: "50050"
    ports:
      - "50050:50050"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - autobot


networks:
  autobot:
    driver: bridge
