FROM node:22-alpine AS builder
WORKDIR /app
COPY apps/wasigap/package*.json ./
RUN npm ci
COPY apps/wasigap/ .
ENV NODE_OPTIONS="--max-old-space-size=2048"
RUN npm run build

FROM node:22-alpine
WORKDIR /app
COPY --from=builder /app/.output .output
EXPOSE 50082
ENV HOST=0.0.0.0
ENV PORT=50082
CMD ["node", ".output/server/index.mjs"]
